### ISSUE TITLE
the game start bus nothing change 

### ISSUE THREAD

**Issue by Zander203** [brokenphilip/OMSIPresence#1]
i've done all as it say but nothing, it don't work for me :(

![#💬𝐁𝐥𝐚𝐛𝐥𝐚-𝐎𝐎𝐂 _ (Southland) Los Santos Fire Department - Discord 23_09_2023 15_04_20](https://github.com/brokenphilip/OMSIPresence/assets/145845968/bb703b02-e686-4e69-9358-adc216d999c0)
![plugins 23_09_2023 15_02_46](https://github.com/brokenphilip/OMSIPresence/assets/145845968/bdf124a0-a4bb-423e-8416-90abd2e4da3b)

**Comment by brokenphilip** [comment]
You've used the "Download ZIP" button (or something similar) from the main page, which contains the source code of the plugin, but NOT the plugin itself (`OMSIPresence.dll` and `OMSIPresence.opl`).

You are supposed to use [the Releases page](https://github.com/brokenphilip/OMSIPresence/releases) instead. However, given that there are no releases yet, I'll try my best to release OMSIPresence in the coming hours/days, depending on my free time.

Please remove the files you've downloaded from your `plugins` folder, and try again once OMSIPresence releases. If you have any issues afterwards, feel free to create a new issue.

Thank you for your interest in the project! :)
